name: Deploy to Cloud Run

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create service account key file
        run: echo "${{ secrets.GCP_SA_KEY }}" > service-account.json

      - name: Set up Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: galery-22579
          credentials_file: service-account.json
          export_default_credentials: true

      - name: Authenticate Docker with GCR
        run: gcloud auth configure-docker

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy etl_unf_payments \
            --source . \
            --region asia-south1 \
            --service-account cloud-run-test@galery-22579.iam.gserviceaccount.com \
            --vpc-connector test-connector \
            --set-env-vars API_AUTH_CODE=${{ secrets.API_AUTH_CODE }} \
            --allow-unauthenticated
